

###
GET http://localhost:3000/products

###
GET http://localhost:3000/products/30

###
DELETE http://localhost:3000/products/1

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "title": "Delivery Drone",
    "price": 1000,
    "description": "A drone that delivers packages to your door",
    "thumbnail": "https://cdn.pixabay.com/photo/2016/03/09/09/22/delivery-1245778_960_720.jpg",
    "category": "drones"
}

###
PATCH http://localhost:3000/products/31
Content-Type: application/json

{
    "price": 1100,
    "description": "A drone that delivers you treasures to your door"
}
