

###
GET http://localhost:3000/api/v1/products

###
GET http://localhost:3000/api/v1/products/30

###
DELETE http://localhost:3000/api/v1/products/1

###
POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
    "title": "Balistic Missile",
    "price": 1000,
    "description": "A missile that can destroy a city",
    "thumbnail": "https://media-cldnry.s-nbcnews.com/image/upload/t_focal-860x484,f_auto,q_auto:best/mpx/2704722219/2024_11/1731932405082_tdy_news_7a_keir_biden_ukraine_241118_1920x1080-00zv90.jpg",
    "category": "weppons"
}

###
PATCH http://localhost:3000/api/v1/products/31
Content-Type: application/json

{
    "price": 1100,
    "description": "A drone that delivers you treasures to your door"
}
